import Head from "next/head";
import Navbar from "../components/navbar";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-[#d8a90f]">
      <Head>
        <title>Stays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div className="h-screen"></div>
      {/* Hero */}
      {/* New Listings */}
      {/* Hero */}
      {/* take action */}
      {/* Hero */}
      {/* blogs */}
      {/* footer */}
    </div>
  );
}
