import Head from "next/head";
import Navbar from "../components/navbar";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Stays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* Hero */}
      {/* New Listings */}
      {/* Hero */}
      {/* take action */}
      {/* Hero */}
      {/* blogs */}
      {/* footer */}
    </>
  );
}
