import Head from "next/head";
import Navbar from "../components/navbar";
import Hero from "../components/hero";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import NewListings from "../components/newListings";
import Footer from "../components/footer";
import {ApolloClient, ApolloProvider, InMemoryCache, useQuery, gql} from "@apollo/client"
import { useObotaQuery } from "../src/generated/graphql";

const inter = Inter({ subsets: ["latin"] });



export default function Home() {
  const { data, loading } = useObotaQuery();

  return (
 

    <div className="">
      <Head>
        <title>Stays</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
      </Head>
      <Navbar />
      {/* Hero */}
      <Hero />

      {/* New Listings */}
      <NewListings />

      {/* take action */}
      {/* blogs */}
      { !data ? (
        <h1>Loading...</h1>
      )
        : <div>{data.obota}</div>
      }

      {/* footer */}
      <Footer />
    </div>
  );
}
